### ISSUE TITLE
license

### ISSUE THREAD

**Issue by fanatid** [dannycoates/int53#1]
Please, set license from [SPDX license list](https://spdx.org/licenses/)

``` shell
$ npm i
npm WARN int53@0.2.3 license should be a valid SPDX license expression
```

**Comment by dannycoates** [comment]
fixed in f382c4b4429fd8f8193793d7f741d3f83e1a7f8f

**Comment by fanatid** [comment]
With https://github.com/dannycoates/int53/commit/f382c4b4429fd8f8193793d7f741d3f83e1a7f8f:

```
$ ./node_modules/.bin/browserify index.js |wc -c
33988
```

`console.assert` uses node assert :smile: https://github.com/Raynos/console-browserify/blob/ab40ed6c90dda556df98f89a4e18b5f9757b6676/index.js#L3

**Comment by dannycoates** [comment]
> console.assert uses node assert

huh, I tested it with the latest browserify and got 3317

**Comment by fanatid** [comment]
``` bash
$ npm ls --depth=0 | grep browserify
`-- browserify@13.0.0 extraneous
$ npm info browserify versions
...
'12.0.2',
'13.0.0' ]
$ ./node_modules/.bin/browserify index.js |wc -c
3317
```

magic...
Thanks for `console.assert` I didn't knew about this!
